### ISSUE TITLE
Expressions wiped from published template spec

### ISSUE THREAD

**Issue by Svessir** [Azure/template-specs#37] opened 2020-10-25 02:11 UTC
I have been using new lines and indents in expressions to make them more readable in my templates. Example:
```json
{
    "variables": {
         "myVar": "[if(equals(parameters('kind'), ''), 
                       variables('resources')[variables('provider')][variables('resourceType')],
                       variables('resources')[variables('provider')][variables('resourceType')][parameters('kind')]))]"
    }
}
```
This works well when I deploy the template normally but when creating a template spec I can see comments and such are removed from the template. Looking at the template in the template spec I would see the above example processed to:
```json
{
    "variables": {
         "myVar": "#Azure Cli#"
    }
}
```
The worst thing is that the template spec will be created successfully instead of throwing an error.

**Comment by alex-frankel** [comment] 2020-10-29 15:51
@Svessir  - do you have the full template that you used to reproduce this behavior? Comments & whitespace are not preserved today, but we should not be changing any of the actual code, so this would indeed be very strange if this was happening.

**Comment by stuartko** [comment] 2020-10-30 01:30
This is only impacting the Az CLI client. @detienne20 will investigate further.

@Svessir : As a workaround you can utilize the Az Powershell cmdlets until this is fixed...

**Comment by detienne20** [comment] 2020-10-31 00:59
We investigated and found the root cause. A fix should be deployed next week.

**Comment by alex-frankel** [comment] 2020-12-21 18:40
Closing - this fix should be deployed in the latest version of Az

**Closed by alex-frankel** 2020-12-21 18:40 UTC
Labels: bug, cli-tooling
